name: Parse VLESS Keys Hourly

on:
  schedule:
    - cron: '0 */4 * * *' # Запускать каждые 4 часа
  workflow_dispatch: # Позволяет запускать вручную

permissions: # Добавляем права на запись контента
  contents: write

jobs:
  parse_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Использовать последнюю стабильную версию Python 3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Configure git and pull changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git pull --rebase origin $(git rev-parse --abbrev-ref HEAD)

      - name: Run parser script
        id: parser
        run: |
          python vpnkeys_parser.py | tee parser_output.txt
          echo "filename=$(grep 'output_filename=' parser_output.txt | cut -d '=' -f2)" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        run: |
          git add ${{ steps.parser.outputs.filename }}
          # Проверяем, есть ли изменения для коммита
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update ${{ steps.parser.outputs.filename }} with latest keys"
            git push # Push to the current branch
          fi 